# Generated by Django 3.1.5 on 2021-01-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MangaList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('url', models.URLField(max_length=300)),
                ('updated', models.BooleanField(default=False)),
            ],
        ),
    ]
