# Generated by Django 3.1.5 on 2021-01-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210115_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mangalist',
            old_name='user_id',
            new_name='user',
        ),
    ]
